// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECOS4-ABk8_2uHlJYtyTN8SmQlbSogA4',
    appId: '1:67013281323:web:b6fc39f779724213ca8c6e',
    messagingSenderId: '67013281323',
    projectId: 'eventquest-1c0af',
    authDomain: 'eventquest-1c0af.firebaseapp.com',
    storageBucket: 'eventquest-1c0af.appspot.com',
    measurementId: 'G-93ZLPGN37G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOOxe5-GVCkClcHI_iuC0TE41nQtHg9qY',
    appId: '1:67013281323:android:fe50fdd2d7105b48ca8c6e',
    messagingSenderId: '67013281323',
    projectId: 'eventquest-1c0af',
    storageBucket: 'eventquest-1c0af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwVUNuGbDZ7qUAOKddGnd0mv2ivGO19Ac',
    appId: '1:67013281323:ios:67c710ad5ad4d0bfca8c6e',
    messagingSenderId: '67013281323',
    projectId: 'eventquest-1c0af',
    storageBucket: 'eventquest-1c0af.appspot.com',
    iosBundleId: 'com.example.lingoPandaAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwVUNuGbDZ7qUAOKddGnd0mv2ivGO19Ac',
    appId: '1:67013281323:ios:67c710ad5ad4d0bfca8c6e',
    messagingSenderId: '67013281323',
    projectId: 'eventquest-1c0af',
    storageBucket: 'eventquest-1c0af.appspot.com',
    iosBundleId: 'com.example.lingoPandaAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDECOS4-ABk8_2uHlJYtyTN8SmQlbSogA4',
    appId: '1:67013281323:web:3652df89d563101bca8c6e',
    messagingSenderId: '67013281323',
    projectId: 'eventquest-1c0af',
    authDomain: 'eventquest-1c0af.firebaseapp.com',
    storageBucket: 'eventquest-1c0af.appspot.com',
    measurementId: 'G-HP71XNLGHQ',
  );
}
